spring:
  cloud:
    nacos:
      server-addr: ${SERVER_ADDR:ENC(j4BGuU4Drn/PCMVnZxSNiVoS29f/oIUfV9FPF6inupI=)}
      username: ${NACOS_SERVER_USER:ENC(qqqHXA1bwhhYPJ9SXXZqyO5j//wygYDK)}
      password: ${NACOS_SERVER_PASSWORD:ENC(v1J0g/bB0xWCi9Te8mwH1o309G9xtm6q1L8SeCkYdYY=)}
      config:
        file-extension: yaml
        namespace: 9623bd6c-3483-4f9e-a40d-1d54e190eb9b
      discovery:
        ip: ${SERVER_ADDR:ENC(BjtXwQuSkFhyspyw2a5BQcd9wVjl/6sZrLVtX4yIQF0=)}
        namespace: 98732302-bf12-40a5-8d93-7f2d97187a12
        cluster-name: BJ
netty:
  address: ${address:ENC(BjtXwQuSkFhyspyw2a5BQcd9wVjl/6sZrLVtX4yIQF0=)}
  maxContentLength: ${MAX_CONTENT_LENGTH:2048}
  websocket:
    port: ${PORT:9111}
    path: ${PATH:/chat}
  protocol: ${PROTOCOL:websocket}
channel:
  handshake:
    wait: ${HANDSHAKE_TIME:5}
